testCommonCode;
   
GInvParam.isParallel = 1;
GInvParam.isPrintBySavingFile = 0;

ids = bsGetIdsFromWelllogs(wellLogs, {'LN206', 'LN2-5-14', 'LN203', 'LN2-4-6', 'LN3-3-10', 'LN320', 'LN302H'});
% ids = 1;
init_ids = bsGetIdsFromWelllogs(wellLogs, {
    'LN12', 'LN203', 'LN3-2-15X', 'LN30', 'LN302H', 'LN33', 'LG202', 'LN2-33-H7', 'LN2-4-6', 'LN2-5-14', 'LN206'});
[inIds, crossIds] = bsGetProfileCrossingWells(GInvParam, wellLogs(init_ids), ...
    'isAlongCrossline', 1, 'method', 'linear');
wells = cell2mat(wellLogs);
wellInIds = [wells.inline];
wellCrossIds = [wells.crossline];
    
[wellPos, wellIndex, wellNames] = bsFindWellLocation(wellLogs, inIds, crossIds);

% inverse a profile
[~, ~, GInvParam, ~, ~, optionsInitModel] = bsBuildInitModel(GInvParam, timeLine, wellLogs(init_ids), ...
    'title', 'cross_well_1ms', ...
    'inIds', [inIds(setdiff(1:length(inIds), wellPos)), wellInIds], ...
    'crossIds', [crossIds(setdiff(1:length(crossIds), wellPos)), wellCrossIds], ...
    'isRebuild', 1, ...
    'p', 2, ...
    'nPointsUsed', 6 ...
);
%     'rangeInline', rangeInline, ...
%     'rangeCrossline', rangeCrossline);


% seisInvOptions.GBOptions.stepTolerance = 1e-8;

% test methods
methods = {
% 1. name:      method name
% 2. flag:      method flag
% 3. regParam:  regularization parameter
% 4. parampkgs: some other information required for regularization
% 5. options:   options for controling inversion process

    struct(...
        'name', '地震数据', ...
        'type', 'Seismic', ...
        'isSaveMat', 0, ...
        'showFiltCoef', 0.5, ...
        'load', struct(...
            'mode', 'segy', ...
            'fileName', GInvParam.preSeisData.fileName, ...
            'segyInfo', GInvParam.preSeisData.segyInfo, ...
            'prestack', 1 ... 
        )...
    );...
    
    struct(...
    'name', '初始模型', ...
    'type', {{'vp', 'vs', 'rho'}}, ...
    'isSaveMat', 0, ...
    'showFiltCoef', GInvParam.initModel.filtCoef, ...
    'load', struct(...
                'mode', 'segy', ...
                'fileName', {{GInvParam.initModel.vp.fileName;...
                             GInvParam.initModel.vs.fileName;...
                             GInvParam.initModel.rho.fileName}}, ...
                'segyInfo', GInvParam.initModel.rho.segyInfo ...
            )...
    );...

    struct(...
        'name', '普通方法', ...
        'flag', 'LFC', ...
        'regParam', 0.7, ...
        'options', bsSetFields(GInvParam.seisInvOptions, {'maxIter', 20;}), ...
        'showFiltCoef', 1, ...
        'isSaveMat', 1, ...
        'isSaveSegy', 0, ...
        'load', struct(...
            'mode', 'off', ...
            'fileName', '' ...
        )...
    );
% 
    struct(...
        'name', '字典反演', ...
        'flag', 'CSR', ...
        'regParam', struct('lambda', 1.4, 'gamma', 0.1), ...
        'parampkgs', bsSetFields(GCSRSparseParam, {'sparsity', 2}), ...
        'options', bsSetFields(GInvParam.seisInvOptions, {'maxIter', 10; 'innerIter', 5; 'initRegParam', 0.7}), ...
        'showFiltCoef', 1, ...
        'isSaveMat', 1, ...
        'isSaveSegy', 1, ...
        'load', struct(...
            'mode', 'off', ...
            'fileName', '' ...
        )...
    );
    
};


% inverse the whole volume
GInvParam.modelSavePath = [basePath, '/inversion_results/'];
% perform the inversion process based on given methods
invResults = bsPreInvTrueMultiTraces(GInvParam, inIds, crossIds, timeLine, methods);
testShowResults;

% add vpvs_ratio and possion property
% [newInvResults, GInvParam, newWellLogs] = bsPreGetOtherAttributesByInvResults(invResults, GInvParam, wellLogs);
% 
% % smooth the inversion results
% % NLMResults = newInvResults;
% % NLMResults(3:end) = bsNLMInvResults(newInvResults(3:end), [], ...
% %     'searchOffset', 4, 'windowSize', [3, 4], 'nPointsUsed', 6, ...
% %     'stride', [1, 1, 1], 'searchStride', [1, 1, 1] ...
% % );
% 
% GShowProfileParam.showLeftTrNumByWells = 500;
% GShowProfileParam.showRightTrNumByWells = 500;
% GShowProfileParam.range.seismic = [-5 5];
% GShowProfileParam.range.vp = [3600 4400];
% GShowProfileParam.range.vs = [1850 2400];
% GShowProfileParam.range.rho = [2.35 2.55];
% GShowProfileParam.range.vpvs_ratio = [1.83 2.08];
% GShowProfileParam.range.possion = [0.295 0.35];
% GShowProfileParam.colormap.allTheSame = bsGetColormap('original');
% GShowProfileParam.isColorReverse = 0;
% 
% GShowProfileParam.scaleFactor = 2;
% GShowProfileParam.showWellOffset = 3;
% 
% GShowProfileParam.showPartVert.upTime = 30;
% GShowProfileParam.showPartVert.downTime = 30;
% GShowProfileParam.showPartVert.mode = 'up_down_time';
% GShowProfileParam.showPartVert.mode = 'off';
% 
% % GShowProfileParam.showPartVert.mode = 'in_2_horizons';
% % GShowProfileParam.showPartVert.horizonIds = [1, 2];
% 
% GShowProfileParam.isShowHorizon = 1;
% reOrganizedResults = bsReOrganizeInvResults(newInvResults);
% % reOrganizedResults = bsReOrganizeInvResults(NLMResults);
% 
% for i = 1 : length(reOrganizedResults)
%     reOrganizedResults{i}.showFiltCoef = 1;
% end
% bsShowPreInvProfiles(GInvParam, GShowProfileParam, reOrganizedResults, newWellLogs, timeLine(1:2));
% set(gcf, 'position', [ 243         107        1677         653]);

