testCommonCode;


GInvParam.isParallel = 1;
GInvParam.isPrintBySavingFile = 1;

[rangeInline, rangeCrossline] = bsGetWorkAreaRange(GSegyInfo, GInvParam.preSeisData.fileName);
[inIds, crossIds] = bsGetCDPsByRange(rangeInline, rangeCrossline);
ids = bsGetIdsFromWelllogs(wellLogs, {'LN206', 'LN2-5-14', 'LN203', 'LN2-4-6', 'LN3-3-10', 'LN320', 'LN302H'});
% % ids = 1;
% 
% [inIds, crossIds] = bsGetProfileCrossingWells(GInvParam, wellLogs(ids), ...
%     'isAlongCrossline', 1);
% inIds = inIds(1:10);
% crossIds = crossIds(1:10);

% inverse a profile
init_ids = bsGetIdsFromWelllogs(wellLogs, {
  'LN203', 'LN30', 'LN3-3-10', 'LG202', 'LN2-33-H7', 'LN2-4-6', 'LN2-5-14', 'LN206'});

[~, ~, GInvParam, ~, ~, optionsInitModel] = bsBuildInitModel(GInvParam, timeLine, wellLogs(init_ids), ...
    'title', '20200331-1ms-radon-volume', ...
    'filtCoef', GInvParam.initModel.filtCoef, ...
    'inIds', inIds, ...
    'crossIds', crossIds, ... 
    'isRebuild', 1, ...
    'p', 2, ...
    'nPointsUsed', 6 ...
);

methods = {
  
    
    struct(...
        'name', '20200332-MATLAB-model-CSR', ...
        'flag', 'CSR', ...
        'regParam', struct('lambda', [0.7 1.2], 'gamma', [0.1 0.4]), ...
        'parampkgs', bsSetFields(GCSRSparseParam, {'sparsity', 2}), ...
        'options', bsSetFields(GInvParam.seisInvOptions, {'maxIter', 6; 'innerIter', 10; 'initRegParam', [0.7 1.2]}), ...
        'showFiltCoef', 1, ...
        'isSaveMat', 1, ...
        'isSaveSegy', 1, ...
        'load', struct(...
            'mode', 'off', ...
            'fileName', '' ...
        )...
    );
    
	struct(...
        'name', '20200332-MATLAB-model-LFC', ...
        'flag', 'LFC', ...
        'regParam', 0.7, ...
        'options', bsSetFields(GInvParam.seisInvOptions, {'maxIter', 20;}), ...
        'showFiltCoef', 1, ...
        'isSaveMat', 1, ...
        'isSaveSegy', 0, ...
        'load', struct(...
            'mode', 'off', ...
            'fileName', '' ...
        )...
    );
};

nMethods = length(methods);

GShowProfileParam.showLeftTrNumByWells = 500;
GShowProfileParam.showRightTrNumByWells = 500;
GShowProfileParam.range.seismic = [-5 5];
GShowProfileParam.range.vp = [3700 4400];
GShowProfileParam.range.vs = [1850 2400];
GShowProfileParam.range.rho = [2.35 2.55];
GShowProfileParam.range.vpvs_ratio = [1.8 2];
GShowProfileParam.range.possion = [0.295 0.35];
GShowProfileParam.colormap.allTheSame = bsGetColormap('original');
GShowProfileParam.isColorReverse = 1;
GShowProfileParam.showWellFiltCoef = 0.6;

GShowProfileParam.scaleFactor = 2;
GShowProfileParam.showWellOffset = 3;

GShowProfileParam.showPartVert.upTime = 40;
GShowProfileParam.showPartVert.downTime = 100;
GShowProfileParam.showPartVert.mode = 'up_down_time';
GShowProfileParam.showPartVert.mode = 'off';

GShowProfileParam.showPartVert.mode = 'in_2_horizons';
GShowProfileParam.showPartVert.horizonIds = [1, 2];

for i = 1 : nMethods
    invResults = bsPreInvTrueMultiTraces(GInvParam, inIds, crossIds, timeLine, methods(i));
    
    [newInvResults, GInvParam, newWellLogs] = bsPreGetOtherAttributesByInvResults(invResults, GInvParam, wellLogs);
    GInvParam.modelSavePath = sprintf('%s/inversion_results/%s/', basePath, methods{i}.name);
    bsWriteInvResultsIntoSegyFiles(GInvParam, newInvResults, 'raw')
    
    freqs = [50 70 90];
    Ks = [1];
    
%     wellLogs(19) = [];
    
    for iDIC = 1 : 2
        switch iDIC
            case 1
                GTrainDICParam = bsCreateGTrainDICParam(...
                    'csr', ...
                    'title', 'HLF', ...
                    'feature_reduction', 1, ...
                    'normalizationMode', 'feat_max_min', ...
                    'isAddTimeInfo', 1, ...
                    'isAddLocInfo', 1, ...
                    'sizeAtom', 90, ...
                    'sparsity', 10, ...
                    'iterNum', 10, ...
                    'nAtom', 300, ...
                    'isRebuild', 1);

            case 2

                GTrainDICParam = bsCreateGTrainDICParam(...
                    'csr', ...
                    'title', 'HLF', ...
                    'feature_reduction', 1, ...
                    'normalizationMode', 'feat_max_min', ...
                    'isAddTimeInfo', 1, ...
                    'isAddLocInfo', 1, ...
                    'sizeAtom', 90, ...
                    'sparsity', 10, ...
                    'iterNum', 10, ...
                    'nAtom', 1000, ...
                    'isRebuild', 1);
                        
        end
                
        for k = 1 : length(freqs)
            for m = 1 : length(Ks)

                [newInvResults, GInvParam1, newWellLogs] = bsPreGetOtherAttributesByInvResults(invResults, GInvParam, wellLogs);
%                 bsShowPreInvProfiles(GInvParam, GShowProfileParam, newInvResults, newWellLogs, timeLine(1:2));
                
                newInvResults{1}.data(1:end-1) = [];
                newInvResults{1}.type(1:end-1) = [];
                outResults1 = bsPreRebuildByCSRWithWholeProcess(GInvParam1, timeLine, newWellLogs, ...
                            methods{i}, newInvResults{1}, sprintf('direct-%s-%dHz-K-%d-DIC-%d', methods{i}.name, freqs(k), Ks(m), iDIC), ...
                            'trainNum', length(newWellLogs), ...
                            'gamma', 1, ...
                            'title', 'HLF', ...
                            'mode', 'low_high', ...
                            'lowCut', freqs(k)/500, ...
                            'highCut', 200/500, ...
                            'wellFiltCoef', GInvParam.initModel.filtCoef, ...
                            'GTrainDICParam', GTrainDICParam, ...
                            'sparsity', Ks(m));

%                 bsShowPreInvProfiles(GInvParam, GShowProfileParam, {outResults1}, newWellLogs, timeLine(1:2));
                
                tmpInvResults = invResults;
                tmpInvResults{1}.data(3) = [];
                tmpInvResults{1}.type(3) = [];
                outResults2 = bsPreRebuildByCSRWithWholeProcess(GInvParam1, timeLine, wellLogs, ...
                            methods{i}, tmpInvResults{1}, sprintf('computed-%s-%dHz-K-%d-DIC-%d', methods{i}.name, freqs(k), Ks(m), iDIC), ...
                            'trainNum', length(newWellLogs), ...
                            'gamma', 1, ...
                            'title', 'HLF', ...
                            'mode', 'low_high', ...
                            'lowCut', freqs(k)/500, ...
                            'highCut', 150/500, ...
                            'wellFiltCoef', GInvParam.initModel.filtCoef, ...
                            'GTrainDICParam', GTrainDICParam, ...
                            'sparsity', Ks(m));

                [finalInvResults, GInvParam2, ~] = bsPreGetOtherAttributesByInvResults({outResults2}, GInvParam, wellLogs);
                finalInvResults{1}.data(1:end-1) = [];
                finalInvResults{1}.type(1:end-1) = [];
                
%                 bsShowPreInvProfiles(GInvParam, GShowProfileParam, finalInvResults, newWellLogs, timeLine(1:2));
                
                bsWriteInvResultsIntoSegyFiles(GInvParam2, finalInvResults, 'HLF');
            end
        end
    end
    
   
end



