testCommonCode;
          
GInvParam.seisInvOptions.GBOptions.isSaveMiddleRes = 1;
GInvParam.seisInvOptions.GBOptions.optAlgHandle = @bsOptLBFGS;
% test methods
methods = {
% 1. name:      method name
% 2. flag:      method flag
% 3. regParam:  regularization parameter
% 4. parampkgs: some other information required for regularization
% 5. options:   options for controling inversion process
    
%     struct(...
%         'name', 'HAGCS-TV', ...
%         'flag', 'HAGCS', ...
%         'regParam', 0.1, ...
%         'parampkgs', [], ...
%         'options', bsSetFields(GInvParam.seisInvOptions, {'regFunc', @bsReg1DTV; ...
%             'addLowFreqConstraint', 1; ...
%             'initRegParam', 0.1}) ...
%     );
    
%     struct(...
%         'name', 'TV', ...
%         'flag', 'TV', ...
%         'regParam', 0.1, ...
%         'parampkgs', struct('diffOrder', 1), ...
%         'options', bsSetFields(GInvParam.seisInvOptions, {'maxIter', 500; 'initRegParam', 0.1}) ...
%     ); 


%     struct(...
%         'name', 'LFC', ...
%         'flag', 'LFC', ...
%         'regParam', 0.2, ...
%         'parampkgs', [], ...
%         'options', bsSetFields(GInvParam.seisInvOptions, {'maxIter', 10}) ...
%     );
% % 
% 
    struct(...
        'name', '1ms-LFC', ...
        'flag', 'LFC', ...
        'regParam', 0.4, ...
        'options', bsSetFields(GInvParam.seisInvOptions, {'maxIter', 15;}), ...
        'showFiltCoef', 1, ...
        'isSaveMat', 1, ...
        'isSaveSegy', 0, ...
        'load', struct(...
            'mode', 'mat', ...
            'fileName', '' ...
        )...
    );

    struct(...
        'name', '1ms-CSR', ...
        'flag', 'CSR', ...
        'regParam', struct('lambda', 1, 'gamma', 0.2), ...
        'parampkgs', bsSetFields(GCSRSparseParam, {'sparsity', 2}), ...
        'options', bsSetFields(GInvParam.seisInvOptions, {'maxIter', 10; 'innerIter', 10; 'initRegParam', 0.4}), ...
        'showFiltCoef', 1, ...
        'isSaveMat', 1, ...
        'isSaveSegy', 1, ...
        'load', struct(...
            'mode', 'off', ...
            'fileName', '' ...
        )...
    );
    
};

% inverse the blind wells
% ids = bsGetIdsFromWelllogs(wellLogs, {'LN206', 'LN2-5-14', 'LN203', 'LN2-4-6', 'LN3-3-10', 'LN320', 'LN302H'});
ids = bsGetIdsFromWelllogs(wellLogs, {'LN3-2-15X'});

init_ids = bsGetIdsFromWelllogs(wellLogs, {'LN3_2_13X'});

% init_ids = bsGetIdsFromWelllogs(wellLogs, {
%     'LG202', 'LN2-33-H7', 'LN2-4-6', 'LN2-5-14', 'LN206'});
% for id = 5 : length(wellLogs)
for id = init_ids
    
    wellInfo = wellLogs{id};

    
    [invVals, model, outputs] = bsPreInvTrueWell(GInvParam, wellInfo, timeLine, methods);

    invVals{1}.name = sprintf('%s: %s', wellInfo.name, invVals{1}.name);
    bsShowPreInvLogResult(GInvParam, GShowProfileParam, invVals, GTrainSSR.filtCoef, 0);
    set(gcf, 'position', [96          54        1243         471]);
end
% bsShowPreFFTResult(GInvParam, GShowProfileParam, invVals, wellInfo);

